import { z } from "zod";
import { authenticateAnonymous, authenticateWithUserID } from "../../utils/auth/index.js";
import { munzeeFetch } from "../../utils/munzee.js";
import { t } from "../../trpc.js";

const alternaMyths = [
  {
    munzee_id: 33026303,
    friendly_name: "Rainbow Unicorn #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/coachV/4249/",
    creator: "coachV",
  },
  {
    munzee_id: 33026304,
    friendly_name: "Rainbow Unicorn #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/geoibsons/3968/",
    creator: "geoibsons",
  },
  {
    munzee_id: 33026308,
    friendly_name: "Rainbow Unicorn #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/dderryberry60/298/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 33026309,
    friendly_name: "Rainbow Unicorn #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/matthewmccann/1654/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 33026310,
    friendly_name: "Rainbow Unicorn #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/RedCarRobbie/237/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 33026311,
    friendly_name: "Rainbow Unicorn #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/fizzypop/89/",
    creator: "fizzypop",
  },
  {
    munzee_id: 33026312,
    friendly_name: "Rainbow Unicorn #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/dafi87/8097/",
    creator: "dafi87",
  },
  {
    munzee_id: 33026313,
    friendly_name: "Rainbow Unicorn #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/VanderArban/779/",
    creator: "VanderArban",
  },
  {
    munzee_id: 33026315,
    friendly_name: "Dan-Dan The Unicorn Man #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/hksfarm/2277/",
    creator: "hksfarm",
  },
  {
    munzee_id: 33026316,
    friendly_name: "Rainbow Unicorn #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/cecie/109/",
    creator: "cecie",
  },
  {
    munzee_id: 33026317,
    friendly_name: "Rainbow Unicorn #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/coolant/1092/",
    creator: "coolant",
  },
  {
    munzee_id: 33026318,
    friendly_name: "Rainbow Unicorn #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/Teraca/76/",
    creator: "Teraca",
  },
  {
    munzee_id: 33026319,
    friendly_name: "Rainbow Unicorn #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/donovanC/1/",
    creator: "donovanC",
  },
  {
    munzee_id: 33026320,
    friendly_name: "Rainbow Unicorn #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/Charis047/20/",
    creator: "Charis047",
  },
  {
    munzee_id: 33026321,
    friendly_name: "Rainbow Unicorn #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/DalenBarb/4076/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 33026322,
    friendly_name: "Rainbow Unicorn #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/4307/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 33026323,
    friendly_name: "Rainbow Unicorn #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/delanamunzee/1/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 33026324,
    friendly_name: "Rainbow Unicorn #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/wylcrawford/57/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 33026325,
    friendly_name: "Rainbow Unicorn #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/BL4CKWAT3R/15/",
    creator: "BL4CKWAT3R",
  },
  {
    munzee_id: 33669369,
    friendly_name: "Rainbow Unicorn #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/Cholland86/10/",
    creator: "Cholland86",
  },
  {
    munzee_id: 33669370,
    friendly_name: "Rainbow Unicorn #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/fixitman/7/",
    creator: "fixitman",
  },
  {
    munzee_id: 33669371,
    friendly_name: "Rainbow Unicorn #23",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/Kirikat/74/",
    creator: "Kirikat",
  },
  {
    munzee_id: 33669372,
    friendly_name: "Rainbow Unicorn #24",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/Raan/24/",
    creator: "Raan",
  },
  {
    munzee_id: 33669373,
    friendly_name: "Rainbow Unicorn #25",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/gmigueis/1/",
    creator: "gmigueis",
  },
  {
    munzee_id: 33669374,
    friendly_name: "Rainbow Unicorn #26",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/AndyCam/1/",
    creator: "AndyCam",
  },
  {
    munzee_id: 55160569,
    friendly_name: "Rainbow Unicorn #27",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/Violetblonde/10/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 33669375,
    friendly_name: "Gnome Leprechaun #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/coachV/4285/",
    creator: "coachV",
  },
  {
    munzee_id: 33669376,
    friendly_name: "Gnome Leprechaun #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/geoibsons/3973/",
    creator: "geoibsons",
  },
  {
    munzee_id: 33669377,
    friendly_name: "Gnome Leprechaun #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/dderryberry60/311/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 33669378,
    friendly_name: "Gnome Leprechaun #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/matthewmccann/1687/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 33669379,
    friendly_name: "Gnome Leprechaun #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/RedCarRobbie/245/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 33669380,
    friendly_name: "Gnome Leprechaun #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/fizzypop/91/",
    creator: "fizzypop",
  },
  {
    munzee_id: 33669381,
    friendly_name: "Gnome Leprechaun #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/dafi87/8216/",
    creator: "dafi87",
  },
  {
    munzee_id: 33669382,
    friendly_name: "Gnome Leprechaun #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/VanderArban/781/",
    creator: "VanderArban",
  },
  {
    munzee_id: 33669383,
    friendly_name: "Gnome Leprechaun #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/Bunchalotta/408/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 33669384,
    friendly_name: "The Roman Gnome  #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/hksfarm/2377/",
    creator: "hksfarm",
  },
  {
    munzee_id: 33669386,
    friendly_name: "Gnome Leprechaun #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/coolant/1095/",
    creator: "coolant",
  },
  {
    munzee_id: 33669387,
    friendly_name: "Gnome Leprechaun #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/Teraca/78/",
    creator: "Teraca",
  },
  {
    munzee_id: 33669388,
    friendly_name: "Gnome Leprechaun #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/donovanC/2/",
    creator: "donovanC",
  },
  {
    munzee_id: 33669389,
    friendly_name: "Gnome Leprechaun #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/Charis047/21/",
    creator: "Charis047",
  },
  {
    munzee_id: 33669390,
    friendly_name: "Gnome Leprechaun #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/DalenBarb/4153/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 33669391,
    friendly_name: "Gnome Leprechaun #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/4389/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 33669392,
    friendly_name: "Gnome Leprechaun #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/delanamunzee/2/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 33669393,
    friendly_name: "Gnome Leprechaun #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/wylcrawford/58/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 33669394,
    friendly_name: "Gnome Leprechaun #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/BL4CKWAT3R/16/",
    creator: "BL4CKWAT3R",
  },
  {
    munzee_id: 33669395,
    friendly_name: "Gnome Leprechaun #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/Cholland86/11/",
    creator: "Cholland86",
  },
  {
    munzee_id: 33669396,
    friendly_name: "Gnome Leprechaun #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/fixitman/8/",
    creator: "fixitman",
  },
  {
    munzee_id: 33669397,
    friendly_name: "Gnome Leprechaun #23",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/Kirikat/75/",
    creator: "Kirikat",
  },
  {
    munzee_id: 33669398,
    friendly_name: "Gnome Leprechaun #24",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/Raan/25/",
    creator: "Raan",
  },
  {
    munzee_id: 33669399,
    friendly_name: "Gnome Leprechaun #25",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/gmigueis/2/",
    creator: "gmigueis",
  },
  {
    munzee_id: 33669400,
    friendly_name: "Gnome Leprechaun #26",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/AndyCam/2/",
    creator: "AndyCam",
  },
  {
    munzee_id: 55160572,
    friendly_name: "Gnome Leprechaun #27",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/Violetblonde/11/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 34234059,
    friendly_name: "Ice Dragon #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/coachV/4294/",
    creator: "coachV",
  },
  {
    munzee_id: 34234060,
    friendly_name: "Ice Dragon #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/geoibsons/3975/",
    creator: "geoibsons",
  },
  {
    munzee_id: 34234061,
    friendly_name: "Ice Dragon #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/dderryberry60/313/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 34234062,
    friendly_name: "Ice Dragon #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/matthewmccann/1691/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 34234063,
    friendly_name: "Ice Dragon #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/RedCarRobbie/252/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 34234064,
    friendly_name: "Ice Dragon #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/dafi87/8300/",
    creator: "dafi87",
  },
  {
    munzee_id: 34234066,
    friendly_name: "Ice Dragon #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/Bunchalotta/409/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 34234067,
    friendly_name: "Ice Dragon Dead Ahead!!! #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/hksfarm/2398/",
    creator: "hksfarm",
  },
  {
    munzee_id: 34234068,
    friendly_name: "Ice Dragon #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/cecie/111/",
    creator: "cecie",
  },
  {
    munzee_id: 34234070,
    friendly_name: "Ice Dragon #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/Teraca/80/",
    creator: "Teraca",
  },
  {
    munzee_id: 34234071,
    friendly_name: "Ice Dragon #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/donovanC/3/",
    creator: "donovanC",
  },
  {
    munzee_id: 34234073,
    friendly_name: "Ice Dragon #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/Charis047/22/",
    creator: "Charis047",
  },
  {
    munzee_id: 34234074,
    friendly_name: "Ice Dragon #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/DalenBarb/4202/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 34234076,
    friendly_name: "Ice Dragon #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/4448/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 34234077,
    friendly_name: "Ice Dragon #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/delanamunzee/3/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 34234078,
    friendly_name: "Ice Dragon #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/wylcrawford/59/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 34234079,
    friendly_name: "Ice Dragon #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/BL4CKWAT3R/17/",
    creator: "BL4CKWAT3R",
  },
  {
    munzee_id: 34234080,
    friendly_name: "Ice Dragon #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/Cholland86/12/",
    creator: "Cholland86",
  },
  {
    munzee_id: 34234081,
    friendly_name: "Ice Dragon #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/fixitman/13/",
    creator: "fixitman",
  },
  {
    munzee_id: 34234082,
    friendly_name: "Ice Dragon #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/Kirikat/77/",
    creator: "Kirikat",
  },
  {
    munzee_id: 34234083,
    friendly_name: "Ice Dragon #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/Raan/30/",
    creator: "Raan",
  },
  {
    munzee_id: 34234084,
    friendly_name: "Ice Dragon #23",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/gmigueis/3/",
    creator: "gmigueis",
  },
  {
    munzee_id: 34234085,
    friendly_name: "Ice Dragon #24",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/AndyCam/3/",
    creator: "AndyCam",
  },
  {
    munzee_id: 55160574,
    friendly_name: "Ice Dragon #25",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/Violetblonde/12/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 34566284,
    friendly_name: "Sasquatch Yeti #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/geoibsons/3977/",
    creator: "geoibsons",
  },
  {
    munzee_id: 34566285,
    friendly_name: "Sasquatch Yeti #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/dderryberry60/315/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 34566286,
    friendly_name: "Sasquatch Yeti #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/matthewmccann/1696/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 34566287,
    friendly_name: "Sasquatch Yeti #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/RedCarRobbie/254/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 34566288,
    friendly_name: "Sasquatch Yeti #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/dafi87/8350/",
    creator: "dafi87",
  },
  {
    munzee_id: 34566289,
    friendly_name: "Sasquatch Yeti #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/VanderArban/783/",
    creator: "VanderArban",
  },
  {
    munzee_id: 34566290,
    friendly_name: "Sasquatch Yeti #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/Bunchalotta/410/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 34566291,
    friendly_name: "Notorious B.I.G.Foot #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/hksfarm/2420/",
    creator: "hksfarm",
  },
  {
    munzee_id: 34566292,
    friendly_name: "Sasquatch Yeti #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/cecie/112/",
    creator: "cecie",
  },
  {
    munzee_id: 34566293,
    friendly_name: "Sasquatch Yeti #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/Teraca/81/",
    creator: "Teraca",
  },
  {
    munzee_id: 34566295,
    friendly_name: "Sasquatch Yeti #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/Charis047/23/",
    creator: "Charis047",
  },
  {
    munzee_id: 34566296,
    friendly_name: "Sasquatch Yeti #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/DalenBarb/4272/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 34566299,
    friendly_name: "Sasquatch Yeti #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/wylcrawford/60/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 34566300,
    friendly_name: "Sasquatch Yeti #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/BL4CKWAT3R/18/",
    creator: "BL4CKWAT3R",
  },
  {
    munzee_id: 34566302,
    friendly_name: "Sasquatch Yeti #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/fixitman/16/",
    creator: "fixitman",
  },
  {
    munzee_id: 34566303,
    friendly_name: "Sasquatch Yeti #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/Kirikat/81/",
    creator: "Kirikat",
  },
  {
    munzee_id: 34566304,
    friendly_name: "Sasquatch Yeti #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/Raan/34/",
    creator: "Raan",
  },
  {
    munzee_id: 34566305,
    friendly_name: "Sasquatch Yeti #23",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/gmigueis/4/",
    creator: "gmigueis",
  },
  {
    munzee_id: 34566306,
    friendly_name: "Sasquatch Yeti #24",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/AndyCam/4/",
    creator: "AndyCam",
  },
  {
    munzee_id: 55160575,
    friendly_name: "Sasquatch Yeti #25",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/Violetblonde/13/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 35176872,
    friendly_name: "Fire Pegasus #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/coachV/4299/",
    creator: "coachV",
  },
  {
    munzee_id: 35176873,
    friendly_name: "Fire Pegasus #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/geoibsons/3981/",
    creator: "geoibsons",
  },
  {
    munzee_id: 35176874,
    friendly_name: "Fire Pegasus #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/dderryberry60/316/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 35176875,
    friendly_name: "Fire Pegasus #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/matthewmccann/1702/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 35176876,
    friendly_name: "Fire Pegasus #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/RedCarRobbie/255/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 35176877,
    friendly_name: "Fire Pegasus #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/dafi87/8419/",
    creator: "dafi87",
  },
  {
    munzee_id: 35176878,
    friendly_name: "Fire Pegasus #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/VanderArban/784/",
    creator: "VanderArban",
  },
  {
    munzee_id: 35176879,
    friendly_name: "Fire Pegasus #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/Bunchalotta/411/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 35176880,
    friendly_name: "Fire! Put it out Yote!!! #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/hksfarm/2421/",
    creator: "hksfarm",
  },
  {
    munzee_id: 35176881,
    friendly_name: "Fire Pegasus #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/cecie/113/",
    creator: "cecie",
  },
  {
    munzee_id: 35176882,
    friendly_name: "Fire Pegasus #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/Teraca/82/",
    creator: "Teraca",
  },
  {
    munzee_id: 35176883,
    friendly_name: "Fire Pegasus #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/donovanC/5/",
    creator: "donovanC",
  },
  {
    munzee_id: 35176884,
    friendly_name: "Fire Pegasus #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/Charis047/24/",
    creator: "Charis047",
  },
  {
    munzee_id: 35176885,
    friendly_name: "Fire Pegasus #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/DalenBarb/4332/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 35176886,
    friendly_name: "Fire Pegasus #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/4614/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 35176887,
    friendly_name: "Fire Pegasus #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/delanamunzee/5/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 35176888,
    friendly_name: "Fire Pegasus #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/wylcrawford/61/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 35176889,
    friendly_name: "Fire Pegasus #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/BL4CKWAT3R/19/",
    creator: "BL4CKWAT3R",
  },
  {
    munzee_id: 35176890,
    friendly_name: "Fire Pegasus #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/Cholland86/15/",
    creator: "Cholland86",
  },
  {
    munzee_id: 35176891,
    friendly_name: "Fire Pegasus #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/fixitman/18/",
    creator: "fixitman",
  },
  {
    munzee_id: 35176894,
    friendly_name: "Fire Pegasus #23",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/gmigueis/5/",
    creator: "gmigueis",
  },
  {
    munzee_id: 55160588,
    friendly_name: "Fire Pegasus #25",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/Violetblonde/16/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 35455206,
    friendly_name: "Cherub #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/coachV/4303/",
    creator: "coachV",
  },
  {
    munzee_id: 35455207,
    friendly_name: "Cherub #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/geoibsons/3984/",
    creator: "geoibsons",
  },
  {
    munzee_id: 35455208,
    friendly_name: "Cherub #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/dderryberry60/317/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 35455209,
    friendly_name: "Cherub #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/matthewmccann/1703/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 35455210,
    friendly_name: "Cherub #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/RedCarRobbie/256/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 35455211,
    friendly_name: "Cherub #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/dafi87/8449/",
    creator: "dafi87",
  },
  {
    munzee_id: 35455212,
    friendly_name: "Cherub #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/VanderArban/785/",
    creator: "VanderArban",
  },
  {
    munzee_id: 35455213,
    friendly_name: "Cherub #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/Bunchalotta/412/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 35455214,
    friendly_name: "CHERub Goddess of Pop #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/hksfarm/2434/",
    creator: "hksfarm",
  },
  {
    munzee_id: 35455215,
    friendly_name: "Cherub #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/cecie/114/",
    creator: "cecie",
  },
  {
    munzee_id: 35455216,
    friendly_name: "Cherub #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/Teraca/83/",
    creator: "Teraca",
  },
  {
    munzee_id: 35455217,
    friendly_name: "Cherub #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/donovanC/6/",
    creator: "donovanC",
  },
  {
    munzee_id: 35455218,
    friendly_name: "Cherub #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/Charis047/25/",
    creator: "Charis047",
  },
  {
    munzee_id: 35455219,
    friendly_name: "Cherub #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/DalenBarb/4348/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 35455220,
    friendly_name: "Cherub #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/4645/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 35455221,
    friendly_name: "Cherub #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/delanamunzee/6/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 35455222,
    friendly_name: "Cherub #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/wylcrawford/62/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 35455223,
    friendly_name: "Cherub #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/BL4CKWAT3R/20/",
    creator: "BL4CKWAT3R",
  },
  {
    munzee_id: 35455224,
    friendly_name: "Cherub #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/Cholland86/16/",
    creator: "Cholland86",
  },
  {
    munzee_id: 35455225,
    friendly_name: "Cherub #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/fixitman/19/",
    creator: "fixitman",
  },
  {
    munzee_id: 35455227,
    friendly_name: "Cherub #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/Kirikat/84/",
    creator: "Kirikat",
  },
  {
    munzee_id: 35455228,
    friendly_name: "Cherub #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/Raan/40/",
    creator: "Raan",
  },
  {
    munzee_id: 35455229,
    friendly_name: "Cherub #23",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/gmigueis/6/",
    creator: "gmigueis",
  },
  {
    munzee_id: 35455230,
    friendly_name: "Cherub #24",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/AndyCam/6/",
    creator: "AndyCam",
  },
  {
    munzee_id: 55160589,
    friendly_name: "Cherub #25",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/cherub.png",
    code: "http://www.munzee.com/m/Violetblonde/17/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 36208786,
    friendly_name: "Ogre #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/coachV/4325/",
    creator: "coachV",
  },
  {
    munzee_id: 36208787,
    friendly_name: "Ogre #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/geoibsons/3985/",
    creator: "geoibsons",
  },
  {
    munzee_id: 36208788,
    friendly_name: "Ogre #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/dderryberry60/318/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 36208789,
    friendly_name: "Ogre #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/matthewmccann/1736/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 36208790,
    friendly_name: "Ogre #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/RedCarRobbie/259/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 36208791,
    friendly_name: "Ogre #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/dafi87/8567/",
    creator: "dafi87",
  },
  {
    munzee_id: 36208792,
    friendly_name: "Ogre #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/VanderArban/786/",
    creator: "VanderArban",
  },
  {
    munzee_id: 36208793,
    friendly_name: "Ogre #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/Bunchalotta/413/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 36208794,
    friendly_name: "Capture me, hurry, get it ogre with! #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/hksfarm/2445/",
    creator: "hksfarm",
  },
  {
    munzee_id: 36208795,
    friendly_name: "Ogre #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/cecie/115/",
    creator: "cecie",
  },
  {
    munzee_id: 36208796,
    friendly_name: "Ogre #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/Teraca/84/",
    creator: "Teraca",
  },
  {
    munzee_id: 36208797,
    friendly_name: "Ogre #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/donovanC/7/",
    creator: "donovanC",
  },
  {
    munzee_id: 36208798,
    friendly_name: "Ogre #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/Charis047/26/",
    creator: "Charis047",
  },
  {
    munzee_id: 36208799,
    friendly_name: "Ogre #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/DalenBarb/4845/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 36208800,
    friendly_name: "Ogre #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/5199/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 36208801,
    friendly_name: "Ogre #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/delanamunzee/7/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 36208802,
    friendly_name: "Ogre #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/wylcrawford/63/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 36208803,
    friendly_name: "Ogre #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/Cholland86/18/",
    creator: "Cholland86",
  },
  {
    munzee_id: 36208805,
    friendly_name: "Ogre #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/Kirikat/98/",
    creator: "Kirikat",
  },
  {
    munzee_id: 36208806,
    friendly_name: "Ogre #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/Raan/69/",
    creator: "Raan",
  },
  {
    munzee_id: 36208807,
    friendly_name: "Ogre #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/gmigueis/7/",
    creator: "gmigueis",
  },
  {
    munzee_id: 36208808,
    friendly_name: "Ogre #23",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/AndyCam/7/",
    creator: "AndyCam",
  },
  {
    munzee_id: 55160586,
    friendly_name: "Ogre #24",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/Violetblonde/14/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 36660526,
    friendly_name: "Chimera #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/coachV/4396/",
    creator: "coachV",
  },
  {
    munzee_id: 36660527,
    friendly_name: "Chimera #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/geoibsons/3994/",
    creator: "geoibsons",
  },
  {
    munzee_id: 36660528,
    friendly_name: "Chimera #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/dderryberry60/323/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 36660529,
    friendly_name: "Chimera #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/matthewmccann/1790/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 36660530,
    friendly_name: "Chimera #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/RedCarRobbie/263/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 36660531,
    friendly_name: "Chimera #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/dafi87/8688/",
    creator: "dafi87",
  },
  {
    munzee_id: 36660532,
    friendly_name: "Chimera #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/VanderArban/787/",
    creator: "VanderArban",
  },
  {
    munzee_id: 36660534,
    friendly_name: "Box of Animal Crackers #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/hksfarm/2481/",
    creator: "hksfarm",
  },
  {
    munzee_id: 36660536,
    friendly_name: "Chimera #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/Teraca/88/",
    creator: "Teraca",
  },
  {
    munzee_id: 36660537,
    friendly_name: "Chimera #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/donovanC/8/",
    creator: "donovanC",
  },
  {
    munzee_id: 36660538,
    friendly_name: "Chimera #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/Charis047/27/",
    creator: "Charis047",
  },
  {
    munzee_id: 36660539,
    friendly_name: "Chimera #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/DalenBarb/5091/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 36660540,
    friendly_name: "Chimera #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/5494/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 36660542,
    friendly_name: "Chimera #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/wylcrawford/64/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 36660543,
    friendly_name: "Chimera #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/Cholland86/19/",
    creator: "Cholland86",
  },
  {
    munzee_id: 36660544,
    friendly_name: "Chimera #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/fixitman/32/",
    creator: "fixitman",
  },
  {
    munzee_id: 36660545,
    friendly_name: "Chimera #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/Kirikat/124/",
    creator: "Kirikat",
  },
  {
    munzee_id: 36660546,
    friendly_name: "Chimera #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/Raan/125/",
    creator: "Raan",
  },
  {
    munzee_id: 36660547,
    friendly_name: "Chimera #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/gmigueis/8/",
    creator: "gmigueis",
  },
  {
    munzee_id: 36660548,
    friendly_name: "Chimera #23",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/AndyCam/8/",
    creator: "AndyCam",
  },
  {
    munzee_id: 55160590,
    friendly_name: "Chimera #24",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/Violetblonde/18/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 38235811,
    friendly_name: "Siren #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/coachV/4539/",
    creator: "coachV",
  },
  {
    munzee_id: 38235812,
    friendly_name: "Siren #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/geoibsons/4106/",
    creator: "geoibsons",
  },
  {
    munzee_id: 38235813,
    friendly_name: "Siren #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/dderryberry60/334/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 38235814,
    friendly_name: "Siren #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/matthewmccann/1841/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 38235815,
    friendly_name: "Siren #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/RedCarRobbie/286/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 38235816,
    friendly_name: "Siren #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/dafi87/8983/",
    creator: "dafi87",
  },
  {
    munzee_id: 38235817,
    friendly_name: "Siren #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/VanderArban/793/",
    creator: "VanderArban",
  },
  {
    munzee_id: 38235818,
    friendly_name: "Siren #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/Bunchalotta/421/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 38235819,
    friendly_name: "Reminds me of someone from way too far ago #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/hksfarm/2697/",
    creator: "hksfarm",
  },
  {
    munzee_id: 38235820,
    friendly_name: "Siren #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/Teraca/97/",
    creator: "Teraca",
  },
  {
    munzee_id: 38235821,
    friendly_name: "Siren #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/Charis047/29/",
    creator: "Charis047",
  },
  {
    munzee_id: 38235822,
    friendly_name: "Siren #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/DalenBarb/5417/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 38235823,
    friendly_name: "Siren #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/5874/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 38235824,
    friendly_name: "Siren #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/delanamunzee/9/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 38235825,
    friendly_name: "Siren #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/wylcrawford/71/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 38235826,
    friendly_name: "Siren #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/Cholland86/29/",
    creator: "Cholland86",
  },
  {
    munzee_id: 38235827,
    friendly_name: "Siren #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/fixitman/45/",
    creator: "fixitman",
  },
  {
    munzee_id: 38235828,
    friendly_name: "Siren #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/Kirikat/147/",
    creator: "Kirikat",
  },
  {
    munzee_id: 38235829,
    friendly_name: "Siren #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/Raan/211/",
    creator: "Raan",
  },
  {
    munzee_id: 38235830,
    friendly_name: "Siren #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/gmigueis/10/",
    creator: "gmigueis",
  },
  {
    munzee_id: 38235831,
    friendly_name: "Siren #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/AndyCam/14/",
    creator: "AndyCam",
  },
  {
    munzee_id: 55160587,
    friendly_name: "Siren #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/siren.png",
    code: "http://www.munzee.com/m/Violetblonde/15/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 49610711,
    friendly_name: "Fairy Godmother #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/coachV/4597/",
    creator: "coachV",
  },
  {
    munzee_id: 49610712,
    friendly_name: "Fairy Godmother #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/geoibsons/4129/",
    creator: "geoibsons",
  },
  {
    munzee_id: 49610713,
    friendly_name: "Fairy Godmother #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/dderryberry60/344/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 49610714,
    friendly_name: "Fairy Godmother #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/matthewmccann/1874/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 49610715,
    friendly_name: "Fairy Godmother #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/RedCarRobbie/291/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 49610716,
    friendly_name: "Fairy Godmother #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/dafi87/9376/",
    creator: "dafi87",
  },
  {
    munzee_id: 49610717,
    friendly_name: "Fairy Godmother #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/VanderArban/796/",
    creator: "VanderArban",
  },
  {
    munzee_id: 49610718,
    friendly_name: "Fairy Godmother #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/Bunchalotta/422/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 49610719,
    friendly_name: "Fairy Godmother #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/hksfarm/3129/",
    creator: "hksfarm",
  },
  {
    munzee_id: 49610721,
    friendly_name: "Fairy Godmother #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/Teraca/102/",
    creator: "Teraca",
  },
  {
    munzee_id: 49610722,
    friendly_name: "Fairy Godmother #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/Charis047/32/",
    creator: "Charis047",
  },
  {
    munzee_id: 49610723,
    friendly_name: "Fairy Godmother #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/DalenBarb/5744/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 49610724,
    friendly_name: "Fairy Godmother #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/6266/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 49610725,
    friendly_name: "Fairy Godmother #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/delanamunzee/11/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 49610726,
    friendly_name: "Fairy Godmother #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/wylcrawford/73/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 49610727,
    friendly_name: "Fairy Godmother #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/Cholland86/106/",
    creator: "Cholland86",
  },
  {
    munzee_id: 49610729,
    friendly_name: "Fairy Godmother #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/Kirikat/169/",
    creator: "Kirikat",
  },
  {
    munzee_id: 49610730,
    friendly_name: "Fairy Godmother #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/Raan/241/",
    creator: "Raan",
  },
  {
    munzee_id: 49610731,
    friendly_name: "Fairy Godmother #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/gmigueis/11/",
    creator: "gmigueis",
  },
  {
    munzee_id: 49610732,
    friendly_name: "Fairy Godmother #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/AndyCam/15/",
    creator: "AndyCam",
  },
  {
    munzee_id: 62507021,
    friendly_name: "Gorgon #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/coachV/4980/",
    creator: "coachV",
  },
  {
    munzee_id: 62507022,
    friendly_name: "Gorgon #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/geoibsons/4186/",
    creator: "geoibsons",
  },
  {
    munzee_id: 62507023,
    friendly_name: "Gorgon #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/dderryberry60/376/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 62507024,
    friendly_name: "Gorgon #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/matthewmccann/1932/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 62507025,
    friendly_name: "Gorgon #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/RedCarRobbie/324/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 62507026,
    friendly_name: "Gorgon #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/dafi87/9966/",
    creator: "dafi87",
  },
  {
    munzee_id: 62507027,
    friendly_name: "Gorgon #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/VanderArban/806/",
    creator: "VanderArban",
  },
  {
    munzee_id: 62507028,
    friendly_name: "Gorgon #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/Bunchalotta/432/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 62507029,
    friendly_name: "Gorgon #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/hksfarm/3679/",
    creator: "hksfarm",
  },
  {
    munzee_id: 62507030,
    friendly_name: "Gorgon #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/Teraca/192/",
    creator: "Teraca",
  },
  {
    munzee_id: 62507031,
    friendly_name: "Gorgon #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/Charis047/42/",
    creator: "Charis047",
  },
  {
    munzee_id: 62507032,
    friendly_name: "Gorgon #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/DalenBarb/6254/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 62507033,
    friendly_name: "Gorgon #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/7094/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 62507034,
    friendly_name: "Gorgon #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/delanamunzee/21/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 62507035,
    friendly_name: "Gorgon #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/wylcrawford/90/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 62507036,
    friendly_name: "Gorgon #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/Cholland86/186/",
    creator: "Cholland86",
  },
  {
    munzee_id: 62507037,
    friendly_name: "Gorgon #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/fixitman/96/",
    creator: "fixitman",
  },
  {
    munzee_id: 62507038,
    friendly_name: "Gorgon #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/Kirikat/220/",
    creator: "Kirikat",
  },
  {
    munzee_id: 62507039,
    friendly_name: "Gorgon #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/Raan/322/",
    creator: "Raan",
  },
  {
    munzee_id: 62507040,
    friendly_name: "Gorgon #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/gmigueis/21/",
    creator: "gmigueis",
  },
  {
    munzee_id: 62507041,
    friendly_name: "Gorgon #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/AndyCam/25/",
    creator: "AndyCam",
  },
  {
    munzee_id: 62507042,
    friendly_name: "Gorgon #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gorgon.png",
    code: "http://www.munzee.com/m/Violetblonde/66/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 72090150,
    friendly_name: "Mother Earth #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/coachV/5902/",
    creator: "coachV",
  },
  {
    munzee_id: 72090151,
    friendly_name: "Mother Earth #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/geoibsons/4295/",
    creator: "geoibsons",
  },
  {
    munzee_id: 72090152,
    friendly_name: "Mother Earth #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/dderryberry60/492/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 72090153,
    friendly_name: "Mother Earth #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/RedCarRobbie/396/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 72090155,
    friendly_name: "Mother Earth #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/Bunchalotta/433/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 72090157,
    friendly_name: "Mother Earth #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/Teraca/418/",
    creator: "Teraca",
  },
  {
    munzee_id: 72090159,
    friendly_name: "Mother Earth #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/DalenBarb/7053/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 72090160,
    friendly_name: "Mother Earth #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/8297/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 72090161,
    friendly_name: "Mother Earth #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/delanamunzee/22/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 72090162,
    friendly_name: "Mother Earth #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/wylcrawford/113/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 72090163,
    friendly_name: "Mother Earth #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/Cholland86/286/",
    creator: "Cholland86",
  },
  {
    munzee_id: 72090164,
    friendly_name: "Mother Earth #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/fixitman/325/",
    creator: "fixitman",
  },
  {
    munzee_id: 72090165,
    friendly_name: "Mother Earth #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/Raan/404/",
    creator: "Raan",
  },
  {
    munzee_id: 72090166,
    friendly_name: "Mother Earth #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/gmigueis/24/",
    creator: "gmigueis",
  },
  {
    munzee_id: 72090167,
    friendly_name: "Mother Earth #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/Kirikat/355/",
    creator: "Kirikat",
  },
  {
    munzee_id: 72090168,
    friendly_name: "Mother Earth #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/AndyCam/26/",
    creator: "AndyCam",
  },
  {
    munzee_id: 53820127,
    friendly_name: " Rob's Hadavale #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/coachV/4704/",
    creator: "coachV",
  },
  {
    munzee_id: 53820128,
    friendly_name: "Hadavale #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/geoibsons/4163/",
    creator: "geoibsons",
  },
  {
    munzee_id: 53820130,
    friendly_name: "Hadavale #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/matthewmccann/1915/",
    creator: "matthewmccann",
  },
  {
    munzee_id: 53820131,
    friendly_name: "Hadavale #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/RedCarRobbie/321/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 53820132,
    friendly_name: "Hadavale #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/dafi87/9644/",
    creator: "dafi87",
  },
  {
    munzee_id: 53820133,
    friendly_name: "Hadavale #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/VanderArban/805/",
    creator: "VanderArban",
  },
  {
    munzee_id: 53820134,
    friendly_name: "Hadavale #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/Bunchalotta/431/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 53820135,
    friendly_name: "Hadavale #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/hksfarm/3619/",
    creator: "hksfarm",
  },
  {
    munzee_id: 53820136,
    friendly_name: "Hadavale #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/Teraca/128/",
    creator: "Teraca",
  },
  {
    munzee_id: 53820138,
    friendly_name: "Hadavale #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/DalenBarb/5930/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 53820139,
    friendly_name: "Hadavale #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/6624/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 53820141,
    friendly_name: "Hadavale #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/wylcrawford/82/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 53820142,
    friendly_name: "Hadavale #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/Cholland86/160/",
    creator: "Cholland86",
  },
  {
    munzee_id: 53820143,
    friendly_name: "Hadavale #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/fixitman/87/",
    creator: "fixitman",
  },
  {
    munzee_id: 53820144,
    friendly_name: "Hadavale #18",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/Kirikat/207/",
    creator: "Kirikat",
  },
  {
    munzee_id: 53820145,
    friendly_name: "Hadavale #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/Raan/293/",
    creator: "Raan",
  },
  {
    munzee_id: 53820146,
    friendly_name: "Hadavale #20",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/gmigueis/20/",
    creator: "gmigueis",
  },
  {
    munzee_id: 53820148,
    friendly_name: "Hadavale #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/Violetblonde/9/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 132927074,
    friendly_name: "Vikerkaar #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/coachV/8131/",
    creator: "coachV",
  },
  {
    munzee_id: 132927075,
    friendly_name: "Vikerkaar #2",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/dderryberry60/788/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 132927076,
    friendly_name: "Vikerkaar #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/RedCarRobbie/775/",
    creator: "RedCarRobbie",
  },
  {
    munzee_id: 132927077,
    friendly_name: "Vikerkaar #4",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/wylcrawford/194/",
    creator: "wylcrawford",
  },
  {
    munzee_id: 132927079,
    friendly_name: "Vikerkaar #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/AndyCam/27/",
    creator: "AndyCam",
  },
  {
    munzee_id: 132927080,
    friendly_name: "Vikerkaar #6",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/11352/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 132927081,
    friendly_name: "Vikerkaar #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/Cholland86/585/",
    creator: "Cholland86",
  },
  {
    munzee_id: 132927082,
    friendly_name: "Vikerkaar #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/Teraca/1189/",
    creator: "Teraca",
  },
  {
    munzee_id: 132927083,
    friendly_name: "Vikerkaar #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/Charis047/48/",
    creator: "Charis047",
  },
  {
    munzee_id: 132927084,
    friendly_name: "Vikerkaar #10",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/DalenBarb/9445/",
    creator: "DalenBarb",
  },
  {
    munzee_id: 132927085,
    friendly_name: "Vikerkaar #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/Kirikat/698/",
    creator: "Kirikat",
  },
  {
    munzee_id: 132927086,
    friendly_name: "Vikerkaar #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/fixitman/653/",
    creator: "fixitman",
  },
  {
    munzee_id: 132927087,
    friendly_name: "Vikerkaar #13",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/Bunchalotta/438/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 132927089,
    friendly_name: "Vikerkaar #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/Raan/491/",
    creator: "Raan",
  },
  {
    munzee_id: 132927090,
    friendly_name: "Vikerkaar #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/gmigueis/25/",
    creator: "gmigueis",
  },
  {
    munzee_id: 132927091,
    friendly_name: "Vikerkaar #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/geoibsons/4420/",
    creator: "geoibsons",
  },
  {
    munzee_id: 132927092,
    friendly_name: "Vikerkaar #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/vikerkaar.png",
    code: "http://www.munzee.com/m/VanderArban/813/",
    creator: "VanderArban",
  },
  {
    munzee_id: 33026314,
    friendly_name: "Rainbow Unicorn #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/rainbowunicorn.png",
    code: "http://www.munzee.com/m/Bunchalotta/406/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 33669385,
    friendly_name: "Gnome Leprechaun #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/gnomeleprechaun.png",
    code: "http://www.munzee.com/m/cecie/110/",
    creator: "cecie",
  },
  {
    munzee_id: 34234065,
    friendly_name: "Ice Dragon #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/icedragon.png",
    code: "http://www.munzee.com/m/VanderArban/782/",
    creator: "VanderArban",
  },
  {
    munzee_id: 34566283,
    friendly_name: "Sasquatch Yeti #1",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/coachV/4296/",
    creator: "coachV",
  },
  {
    munzee_id: 34566294,
    friendly_name: "Sasquatch Yeti #12",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/donovanC/4/",
    creator: "donovanC",
  },
  {
    munzee_id: 34566297,
    friendly_name: "Sasquatch Yeti #15",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/SpaceCoastGeoStore/4525/",
    creator: "SpaceCoastGeoStore",
  },
  {
    munzee_id: 34566298,
    friendly_name: "Sasquatch Yeti #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/delanamunzee/4/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 34566301,
    friendly_name: "Sasquatch Yeti #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/sasquatchyeti.png",
    code: "http://www.munzee.com/m/Cholland86/14/",
    creator: "Cholland86",
  },
  {
    munzee_id: 35176892,
    friendly_name: "Fire Pegasus #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/Kirikat/83/",
    creator: "Kirikat",
  },
  {
    munzee_id: 35176893,
    friendly_name: "Fire Pegasus #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/Raan/38/",
    creator: "Raan",
  },
  {
    munzee_id: 35176895,
    friendly_name: "Fire Pegasus #24",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/firepegasus.png",
    code: "http://www.munzee.com/m/AndyCam/5/",
    creator: "AndyCam",
  },
  {
    munzee_id: 36208804,
    friendly_name: "Ogre #19",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/ogre.png",
    code: "http://www.munzee.com/m/fixitman/26/",
    creator: "fixitman",
  },
  {
    munzee_id: 36660533,
    friendly_name: "Chimera #8",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/Bunchalotta/414/",
    creator: "Bunchalotta",
  },
  {
    munzee_id: 36660541,
    friendly_name: "Chimera #16",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/chimera.png",
    code: "http://www.munzee.com/m/delanamunzee/8/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 49610728,
    friendly_name: "Fairy Godmother #17",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/fixitman/55/",
    creator: "fixitman",
  },
  {
    munzee_id: 55160595,
    friendly_name: "Fairy Godmother #22",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/fairygodmother.png",
    code: "http://www.munzee.com/m/Violetblonde/19/",
    creator: "Violetblonde",
  },
  {
    munzee_id: 72090154,
    friendly_name: "Mother Earth #5",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/VanderArban/807/",
    creator: "VanderArban",
  },
  {
    munzee_id: 72090156,
    friendly_name: "Mother Earth #7",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/hksfarm/5109/",
    creator: "hksfarm",
  },
  {
    munzee_id: 72090158,
    friendly_name: "Mother Earth #9",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/motherearth.png",
    code: "http://www.munzee.com/m/Charis047/44/",
    creator: "Charis047",
  },
  {
    munzee_id: 53820129,
    friendly_name: "Hadavale #3",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/dderryberry60/372/",
    creator: "dderryberry60",
  },
  {
    munzee_id: 53820137,
    friendly_name: "Hadavale #11",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/Charis047/41/",
    creator: "Charis047",
  },
  {
    munzee_id: 53820140,
    friendly_name: "Hadavale #14",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/delanamunzee/20/",
    creator: "delanamunzee",
  },
  {
    munzee_id: 53820147,
    friendly_name: "Hadavale #21",
    munzee_logo: "https://munzee.global.ssl.fastly.net/images/pins/hadavale.png",
    code: "http://www.munzee.com/m/AndyCam/24/",
    creator: "AndyCam",
  },
];
alternaMyths.sort((a, b) => a.munzee_id - b.munzee_id);

export const alternamythRouter = t.router({
  captures: t.procedure
    .input(
      z.object({
        username: z.string(),
      })
    )
    .query(async ({ input: { username } }) => {
      const anonToken = await authenticateAnonymous();
      const { data: user } = await munzeeFetch({
        endpoint: "user",
        params: {
          username,
        },
        token: anonToken,
      }).then(i => i.getMunzeeData());

      if (!user?.user_id) {
        return null;
      }

      const userId = user.user_id;

      const token = await authenticateWithUserID(userId);
      const response = await munzeeFetch({
        endpoint: "munzee/hascaptured",
        params: { munzee_ids: alternaMyths.map(i => i.munzee_id).join(",") },
        token,
      });
      const data = await response.getMunzeeData();

      return {
        alternaMyths: alternaMyths.map(i => ({
          ...i,
          captured: !!data.data?.[i.munzee_id],
        })),
      };
    }),
});
